# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(Dialog,clicked = lambda: self.backup())
        self.pushButton.setGeometry(QtCore.QRect(10, 250, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 250, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 160, 123))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 201, 41))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 190, 171, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)

        ##
        self.textEdit.setDisabled(True)
        self.checkBox.toggled.connect(self.textEdit.setEnabled)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Backup"))
        self.pushButton_2.setText(_translate("Dialog", "Restore"))
        self.checkBox_3.setText(_translate("Dialog", "Shaders"))
        self.checkBox_2.setText(_translate("Dialog", "Mods"))
        self.checkBox.setText(_translate("Dialog", "World"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Minecraft Backup And Restore</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Name:"))
    def backup(self):
        if self.checkBox.isChecked() == True:
            mc_path = get_path()
            if sys.platform == "linux":
                mc_path = mc_path + '/saves'
            else:
                mc_path = mc_path + '\saves'
            name, done1 = QtWidgets.QInputDialog.getText(
                self, 'Input Dialog', 'Enter your name:')
            target = input("Enter World Name: ")      

            desktop_dir = Path.home().joinpath('Desktop')
            os.chdir(mc_path)
            print("Compressing please wait..")
            make_archive(target, "zip", target)
            os.system(f"cp -r '{target}.zip' {desktop_dir}")
            os.remove(f"{target}.zip")
            if os.path.isfile(f"{desktop_dir}/.minecraft.zip"):
                os.rename(f"{desktop_dir}/.minecraft.zip", f"{desktop_dir}/minecraft.zip")
                target = "minecra"
            print("Backup located at Desktop : " + target)
            os.chdir(desktop_dir)
            open_location()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
